# Generated by Django 4.1.6 on 2023-02-07 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Название сервиса')),
                ('description', models.CharField(max_length=3000, null=True, verbose_name='Описание сервиса')),
                ('price', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость услуги')),
                ('duration', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(499000)], verbose_name='Продолжительность услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
            ],
            options={
                'verbose_name': 'Cервис',
                'verbose_name_plural': 'Cервисы',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=30, null=True, verbose_name='Дата начала')),
                ('end_date', models.CharField(max_length=30, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('1', 'Active'), ('0', 'Not Active')], default='0', max_length=200, verbose_name='Статус услуги')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='payments.service', verbose_name='Услуга')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сервиса')),
            ],
            options={
                'verbose_name': 'Статус сервиса',
                'verbose_name_plural': 'Статус сервисов',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('amount', models.CharField(max_length=30, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('description', models.CharField(max_length=3000, null=True, verbose_name='Описание услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('Not paid', 'Заказ не оплачен'), ('Rejected', 'Заказ отклонён'), ('Paid', 'Заказ оплачен')], default='Not paid', max_length=200, verbose_name='Статус услуги')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='payments.service', verbose_name='Пользователь сервиса')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь сервиса')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
