# Generated by Django 4.1.6 on 2023-02-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatus',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='payments.order', verbose_name='Заказ'),
        ),
    ]
