# Generated by Django 4.1.7 on 2023-03-09 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='servicestatus',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
    ]
