version: '3'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate && gunicorn enimi.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./static:/enimi/static
      - ./logs:/enimi/logs:rw
      - ./uploads:/enimi/uploads:rw
    environment:
      - SECRET_KEY=django-insecure-gr2ik%t(twxbx+97r=(@g9i$fd6+1aua95phyp(p71!p+w3rwg
      - DB_NAME=enimi_db
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=5432
    expose:
      - "8000"
      - "5432"
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_DB=enimi_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 10s
      retries: 5
    env_file:
      - ./.env
      
  nginx:
    build: ./nginx
    volumes:
        - ./static:/home/user/enimi/static
        - ./uploads:/home/user/enimi/uploads:rw
    ports:
      - 8000:80
    depends_on:
      - web
      
volumes:
  postgresql_data:
  static:
  uploads:
  