# Generated by Django 4.1.4 on 2022-12-28 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_tutors', '0005_education_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
