# Generated by Django 4.1.4 on 2022-12-28 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_tutors', '0006_alter_tutormodule_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorCabinets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'муж.'), ('female', 'жен.')], default=None, max_length=150, null=True, verbose_name='Пол')),
                ('about', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Коротко о себе')),
                ('education', models.ManyToManyField(related_name='tutors', to='cabinet_tutors.education', verbose_name='Образование и дипломы')),
            ],
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='Languages',
        ),
        migrations.DeleteModel(
            name='TutorModule',
        ),
        migrations.AddField(
            model_name='tutorcabinets',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='tutors', to='cabinet_tutors.languages', verbose_name='Язык преподавания'),
        ),
        migrations.AddField(
            model_name='tutorcabinets',
            name='study_formats',
            field=models.ManyToManyField(related_name='tutors', to='cabinet_tutors.studyformats', verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='tutorcabinets',
            name='subjects_and_costs',
            field=models.ManyToManyField(related_name='tutors', to='cabinet_tutors.subjectsandcosts', verbose_name='Предметы и стоимость'),
        ),
        migrations.AddField(
            model_name='tutorcabinets',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
