# Generated by Django 4.1.4 on 2023-01-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet_parents", "0011_alter_survey_student_area_alter_survey_tutor_area"),
        (
            "cabinet_tutors",
            "0008_subjectsandcosts_cost_subjectsandcosts_experience_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectsandcosts",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutors",
                to="cabinet_parents.subject",
                verbose_name="Предмет",
            ),
        ),
    ]
