# Generated by Django 4.1.5 on 2023-02-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0015_alter_city_city_alter_district_district_and_more'),
        ('cabinet_tutors', '0014_remove_mystudent_student_mystudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorstudyformats',
            name='student_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutors', to='cabinet_parents.studentarea', verbose_name='Район занятий у ученика'),
        ),
    ]
