# Generated by Django 4.1.4 on 2023-02-25 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_tutors', '0015_tutorstudyformats_student_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsandcosts',
            name='experience',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(499000)], verbose_name='Опыт преподавания'),
        ),
    ]
