# Generated by Django 4.1.6 on 2023-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membereventrating',
            name='score',
            field=models.SmallIntegerField(null=True, verbose_name='Оценка'),
        ),
    ]
