# Generated by Django 4.1.4 on 2022-12-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_with_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TutorModule',
        ),
    ]
