# Generated by Django 4.1.6 on 2023-02-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_merge_0007_account_with_email_0007_delete_tutormodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.CharField(blank=True, max_length=30, verbose_name='Дата рождения'),
        ),
    ]
