# Generated by Django 4.1.6 on 2023-02-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, max_length=30, verbose_name='Дата рождения'),
        ),
    ]
