# Generated by Django 4.1.4 on 2023-01-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet_tutors", "0011_tutorstudyformats_alter_education_options_and_more"),
        ("cabinet_parents", "0011_alter_survey_student_area_alter_survey_tutor_area"),
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="cabinet_tutor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="cabinet_tutors.tutorcabinets",
                verbose_name="Анкета репетитора",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="survey",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="cabinet_parents.survey",
                verbose_name="Анкета студента",
            ),
        ),
    ]
