# Generated by Django 4.1.4 on 2022-12-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tutormodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodule',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_module', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
