# Generated by Django 4.1.4 on 2022-12-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='with_survey',
            field=models.BooleanField(default=False, verbose_name='Анкета есть'),
        ),
    ]
