# Generated by Django 4.1.4 on 2022-12-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_with_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='with_email',
            field=models.BooleanField(default=True, verbose_name='Email есть'),
        ),
    ]
