# Generated by Django 4.1.4 on 2023-01-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_account_with_email"),
        ("accounts", "0007_delete_tutormodule"),
    ]

    operations = []
