# Generated by Django 4.1.4 on 2023-01-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0002_auto_20210717_1606"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventmember",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
