# Generated by Django 4.1.5 on 2023-01-18 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calendarapp', '0004_alter_eventmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
