# Generated by Django 4.1.6 on 2023-02-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_eventformat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_format',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendarapp.eventformat'),
        ),
    ]
