# Generated by Django 4.1.4 on 2022-12-28 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_tutors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Учебное заведение')),
                ('speciality', models.CharField(blank=True, max_length=200, null=True, verbose_name='Специальность')),
                ('degree', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полученная степень')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Язык')),
            ],
        ),
        migrations.CreateModel(
            name='TutorModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.CharField(blank=True, max_length=50, null=True, verbose_name='Дата рождения')),
                ('gender', models.CharField(blank=True, choices=[('male', 'муж.'), ('female', 'жен.')], default='male', max_length=150, null=True, verbose_name='Пол')),
                ('about', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Коротко о себе')),
                ('education', models.ManyToManyField(related_name='education_and_costs', to='cabinet_tutors.education', verbose_name='Образование и дипломы')),
                ('language', models.ManyToManyField(blank=True, related_name='languages', to='cabinet_tutors.language', verbose_name='Язык преподавания')),
                ('study_formats', models.ManyToManyField(related_name='study_formats', to='cabinet_tutors.studyformats', verbose_name='Формат обучения')),
                ('subjects_and_costs', models.ManyToManyField(related_name='subjects_and_costs', to='cabinet_tutors.subjectsandcosts', verbose_name='Предметы и стоимость')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_module', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutTutor',
        ),
        migrations.DeleteModel(
            name='TutorEducationAndDiplomas',
        ),
    ]
