# Generated by Django 4.1.4 on 2022-12-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_tutors', '0002_education_language_tutormodule_delete_abouttutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutormodule',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'муж.'), ('female', 'жен.')], default=None, max_length=150, null=True, verbose_name='Пол'),
        ),
    ]
