# Generated by Django 4.1.4 on 2023-01-10 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet_tutors", "0009_alter_subjectsandcosts_subject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subjectsandcosts",
            options={"ordering": ["id"]},
        ),
    ]
