# Generated by Django 4.1.4 on 2023-01-12 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet_parents", "0011_alter_survey_student_area_alter_survey_tutor_area"),
        ("cabinet_tutors", "0010_alter_subjectsandcosts_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TutorStudyFormats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активный"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалено"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения"),
                ),
                (
                    "online",
                    models.ManyToManyField(
                        related_name="tutors",
                        to="cabinet_parents.onlineplatform",
                        verbose_name="Онлайн платформы",
                    ),
                ),
                (
                    "tutor_area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tutors",
                        to="cabinet_parents.tutorarea",
                        verbose_name="Район занятий у репетитора",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["id"]},
        ),
        migrations.RemoveField(
            model_name="tutorcabinets",
            name="study_formats",
        ),
        migrations.DeleteModel(
            name="StudyFormats",
        ),
        migrations.AddField(
            model_name="tutorcabinets",
            name="study_formats",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tutors",
                to="cabinet_tutors.tutorstudyformats",
                verbose_name="Формат обучения",
            ),
        ),
    ]
