# Generated by Django 4.1.5 on 2023-01-18 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinet_tutors', '0011_tutorstudyformats_alter_education_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('tutor', models.ManyToManyField(related_name='tutors', to=settings.AUTH_USER_MODEL, verbose_name='Репетитор')),
            ],
        ),
    ]
