# Generated by Django 4.1.4 on 2023-01-03 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0002_survey_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='max_cost',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500000)], verbose_name='Максимальная стоимость тг./час'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='min_cost',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(499000)], verbose_name='Минимальная стоимость тг./час'),
        ),
    ]
