# Generated by Django 4.1.4 on 2023-01-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0004_studentarea_tutorarea_remove_tutorregion_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='education_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cabinet_parents.educationtime', verbose_name='Время для обучения'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='student_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cabinet_parents.studentarea', verbose_name='Район занятий у ученика'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tutor_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cabinet_parents.tutorarea', verbose_name='Район занятий у репетитора'),
        ),
    ]
