# Generated by Django 4.1.4 on 2023-01-03 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0007_remove_survey_student_area_remove_survey_tutor_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorarea',
            name='survey',
        ),
        migrations.AddField(
            model_name='survey',
            name='student_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cabinet_parents.studentarea', verbose_name='Район занятий у ученика'),
        ),
        migrations.AddField(
            model_name='survey',
            name='tutor_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cabinet_parents.tutorarea', verbose_name='Район занятий у репетитора'),
        ),
    ]
