# Generated by Django 4.1.4 on 2023-01-04 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0009_alter_survey_student_area_alter_survey_tutor_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='student_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cabinet_parents.studentarea', verbose_name='Район занятий у ученика'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tutor_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='cabinet_parents.tutorarea', verbose_name='Район занятий у репетитора'),
        ),
        migrations.AlterField(
            model_name='tutorarea',
            name='tutor_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_areas', to='cabinet_parents.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='tutorarea',
            name='tutor_district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_areas', to='cabinet_parents.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='tutorarea',
            name='tutor_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_areas', to='cabinet_parents.region', verbose_name='Область'),
        ),
    ]
