# Generated by Django 4.1.4 on 2023-01-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0010_alter_survey_student_area_alter_survey_tutor_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='student_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='cabinet_parents.studentarea', verbose_name='Район занятий у ученика'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='tutor_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='cabinet_parents.tutorarea', verbose_name='Район занятий у репетитора'),
        ),
    ]
