# Generated by Django 4.1.5 on 2023-01-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='description',
        ),
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.CharField(default=1, max_length=500, verbose_name='Уведомление'),
            preserve_default=False,
        ),
    ]
