# Generated by Django 4.1.5 on 2023-01-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notifications_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='type',
            field=models.CharField(choices=[('response', 'Отклик'), ('chat', 'Чат'), ('registration', 'Регистрация'), ('adding_student', 'Добавление ученика')], max_length=200, verbose_name='Пол'),
        ),
    ]
