# Generated by Django 4.1.4 on 2022-12-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='tests',
            field=models.ManyToManyField(related_name='surveys', to='cabinet_parents.test', verbose_name='Программа тестов'),
        ),
    ]
