# Generated by Django 4.1.4 on 2023-01-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cabinet_parents", "0013_alter_city_city_alter_district_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city",
            field=models.CharField(
                blank=True, default="Не указано", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="district",
            field=models.CharField(
                blank=True, default="Не указано", max_length=100, verbose_name="Город"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region",
            field=models.CharField(
                blank=True, default="Не указано", max_length=100, verbose_name="Область"
            ),
        ),
    ]
