# Generated by Django 4.1.6 on 2023-02-08 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet_parents', '0016_alter_district_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cabinet_parents.region', verbose_name='Области'),
        ),
    ]
